name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d77846b42f0433f9fd36e3cbb0ff5620f9ec35424c412e3235be537d8b2d8f7"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
