name = "Tiny Tater Test modpack (AOF)"
author = "Tiny Taters"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd7686b9fe5c68548e4183c39a3a890a4b4408dd2055a7d0cb713b7a0438510c"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
