name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.9"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67515fe7af448b577c17bf60bedca29fb73a40b443e39c902148df25d6356156"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
