name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b478f7fc1f4e734a9140b5478933d76dfbb405017ba44d9c42e8cd5c281d49bc"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
