name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa73e52f470a87d8419edc3ccd956ee9fc77ba546fb1fccbeab293cb5aae09ff"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
