name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fc7cc364a2d1edba5d409385eccd0058acda7a77bd180b6af060c176c8f2425"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
