name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e6c603b0b19db1d9a95d08a05924c11e80c9595a575fc42a2a470c8fe12c31a"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
