name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "686b3c7e7a388d36470fcee65f697a81dfda4c881e85f811b0663a94b972d4e0"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
