name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.7"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb7b1946a1cd2846314a1703774eb62a03c53abe617082ab4f856d832278f4d1"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
