name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "993cc1b61794c5db83a356dda32beae8a8c895fe47852f7400318ba37df61d62"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
