name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1547e766fd5d121de6feff42967e849465484440784a7f9a2c7909bb2a9416d"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
