name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "741874f05ac5cc317693579f6ca8ac4c95f75fce83aefc10f6d170b7711bf5aa"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
