name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.7"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7beace81d9d23689c56022848f6a0f446639398b62c93eaec9cf178776c2327"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
