name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c92e312f54dc172b07068ccfb81ed8fb791997255e140cb6e0c7072602a58608"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
