name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "636a5073c38070db552023e22cac2f17e5eaf4f33473f6bccdaca7801e271b2f"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
