name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.12"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c6f20a29dab5ce8911ce7fa95da8219086cd6f1b0c0d4be6d588ef912b0e811"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
