name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28eb06f68154eda8d520f08c217dcac697fcf7aaccf9bfe3d085b6b10bac9f41"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
