name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.13"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8c256c16731e34de1e2b0096137c88233ee6ea00c21cafce6aaeebc8f685907"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
