name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6052afe4a664547fef5ada21a3a0acf02eb905723befa733cdbd5d8d13c0ade"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
