name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5425df88c1913332e1757b85456cd76674c974d2151455967f083f68ef9478ec"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
