name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e0f713276ee7a562befd45f78d9455b66046ee873ade9e6e611db535daac461"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
