name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.11"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58487e2a1a46c5247d5d2db1a6942c0312f88fe8a02c3bdf90e043ce6f81fb20"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
