name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98427f364eeda27816506556787126425b242a9a97e0a66a9a58c6224d293f7a"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
