name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d035ac234dab99fb95c7b6df0c994ea2b63a6d262ac01767a3f452ea14dadaff"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
