name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97265df4d56a196b2e42b7bb0956db45c3d090e8b49f9b33217ff0ce689e702e"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
