name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6103ef72f44e6642ba812e89222e24cf946bb161fbf030018673fbb1cad21838"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
