name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.10"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76c3ac068510c18e8694b93c432c47cd7cf8c235d0f5b902936d985f8fc4e88c"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
