name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bcc9b8f7af6e8cf3a7eb5bf67a7c22c3b1136e3ecae2eeaddd24edef947cee0"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
