name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.7"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41113dac6a2d368470caaf9ce9b8222dd365718ee25a1319860ad0a0428bddd1"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
