name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6c10ef4b450b00f7e37fbcd210e4d2a1860f6dd90c67a403e051cbad79fba05"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
