name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ae5179ab488e67ff17d4c912198ee1e0ecc63584295d6f17c63e773859e3d1f"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
