name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fac6228d12041dbbb1f865f74965876aa9e0804936cba7140f66d2ede953e6ac"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
