name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.13"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3af9e5eb5e16f2602cfd12ee59db86d2d2d104add068b26ff8f7c76cad7a95f"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
