name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.7"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00774446dfa8161768a689ce4102b97c9bf8890745a10d600cd2f142a4f8e2f8"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
