name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.10"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a61027052d4cc33b91e847cfff851958fcd33d23261ea27f2456e2932ec8792c"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
