name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cdeac98badced6258d3aee2a0ac15c2c9e57f1bd7b80f534bc9dd2b31f289fa"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
