name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f6c5e4aba79279110b1171aedcd950def8d3e09017b11611fc1c408aa515848"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
