name = "Tiny Tater Test modpack (AOF)"
author = "Tiny Taters"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fd9505556bf3504ea1d39a8aa515142bf0718782714d342d5d780fc6b23b033"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
