name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7beae87a15a9c9783c0315c154fee98e1bc0fddb1c2194f1e9ba3fe145d4532"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
