name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.14"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "791f5fc3cddc9603d9f0b89380aed95554529ac39b603fe4cdd608975e064bf3"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
