name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.15"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea4394ebc4c5bbfd705b5b8cbb7fed36fcfb71293e8d725b084c0df3e5397da2"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
