name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77d7084040936d545fd3ff7e66b4d230080fc8a4c01e5a105e2d5c88efdc1f7d"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
