name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7103b656f6e5baabf7ca95176057be75b368ee38e50776c7af13acd9f9fd6883"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
