name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad8b502d8af7d460d28452a844957cd0569320d6dadc924beac46b338285dd9c"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
