name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c365723b0853695a8b7a552ae12a2296d4fb8e0afe5b72df5428e7fe138d581"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
