name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ae678733fa51d1de257a0c6de400c40731643dcd60bb31a0b781e2ee6d480d5"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
