name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd3300729523bfe3052b9c72116c24bf7f678a3d7c45ad86b531fb71ea13aafd"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
