name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.7"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de1add326aa3af6dc9fb6a932d15d1a71a9d7de693c4b23dfae84e5fd15b995b"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
