name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a422767a20c4f38f46eed38405d98b3207535d7a9eb357a86e289172f6e0699"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
