name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92cf5252e706e5df519f490cf4bbfcd49808292f8ea62996e1adb7779b269782"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
