name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.15"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b04d8f4ba2e9d38ab4c64e54ab7eb8e411f38956e97c52033246237ff008c6ae"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
