name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf11b5f3e82098372c0d0e870b5af9d6a4e3398e83f6c967b5c67277ee22a132"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
