name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d684e6fe01963bd757e9ef919cf7e1b4aff0fec4e7b7a85fdf88e75113d7476"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
