name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fba60a1642903deca273170c764393141ac43665992354df93b77c122932e2b5"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
