name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fb21a4c66acb0453fb89fe384da53fcdf3ffa4ffeca89dfd0e246f1043baca3"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
