name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.7"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02c701c5dc7bd4c300755a2d807609b99206c7cc47d45c136690e1ef52c28b24"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
