name = "Tiny Tater Test server (AOF)"
author = "Tiny Taters, Team AOF"
version = "1.1.14"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37fc180cde784292203c4838803ff9b8518590cc79cb0ac6dd10026e40c3a58a"

[versions]
fabric = "0.11.1"
minecraft = "1.16.5"
