name = "Architectury API (Fabric)"
filename = "architectury-1.8.120-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3214/319/architectury-1.8.120-fabric.jar"
hash-format = "murmur2"
hash = "1730177272"

[update]
[update.curseforge]
file-id = 3214319
project-id = 419697
release-channel = "beta"
