name = "Architectury API (Fabric)"
filename = "architectury-1.5.110-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3197/21/architectury-1.5.110-fabric.jar"
hash-format = "murmur2"
hash = "2605561276"

[update]
[update.curseforge]
file-id = 3197021
project-id = 419697
release-channel = "beta"
