name = "Biome Makeover"
filename = "biome-makeover-1.16.4-1.2.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3186/42/biome-makeover-1.16.4-1.2.10.jar"
hash-format = "murmur2"
hash = "674617360"

[update]
[update.curseforge]
file-id = 3186042
project-id = 412182
release-channel = "beta"
