name = "Biome Locator"
filename = "biome_locator-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3197/135/biome_locator-1.1.0.jar"
hash-format = "murmur2"
hash = "3366968817"

[update]
[update.curseforge]
file-id = 3197135
project-id = 436799
release-channel = "beta"
