name = "Biome Locator"
filename = "biome_locator-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/516/biome_locator-1.1.1.jar"
hash-format = "murmur2"
hash = "1564008728"

[update]
[update.curseforge]
file-id = 3198516
project-id = 436799
release-channel = "beta"
