name = "Bits And Chisels"
filename = "bitsandchisels-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3182/544/bitsandchisels-2.0.0.jar"
hash-format = "murmur2"
hash = "3152887204"

[update]
[update.curseforge]
file-id = 3182544
project-id = 420709
release-channel = "beta"
