name = "Boring Backgrounds"
filename = "boringbackgrounds-3.0.2+1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3063/862/boringbackgrounds-3.0.2+1.16.3.jar"
hash-format = "murmur2"
hash = "1823315564"

[update]
[update.curseforge]
file-id = 3063862
project-id = 363126
release-channel = "beta"
