name = "Campanion"
filename = "campanion-1.3.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3205/486/campanion-1.3.4.jar"
hash-format = "murmur2"
hash = "2072558117"

[update]
[update.curseforge]
file-id = 3205486
project-id = 373138
release-channel = "beta"
