name = "Cardinal Components"
filename = "Cardinal-Components-API-2.7.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3204/874/Cardinal-Components-API-2.7.12.jar"
hash-format = "murmur2"
hash = "2268938868"

[update]
[update.curseforge]
file-id = 3204874
project-id = 318449
release-channel = "beta"
