name = "Carrier"
filename = "carrier-1.7.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3198/165/carrier-1.7.4.jar"
hash-format = "murmur2"
hash = "2049577886"

[update]
[update.curseforge]
file-id = 3198165
project-id = 409184
release-channel = "beta"
