name = "Charmonium"
filename = "charmonium-fabric-1.16.4-2.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3157/618/charmonium-fabric-1.16.4-2.2.2.jar"
hash-format = "murmur2"
hash = "4042596929"

[update]
[update.curseforge]
file-id = 3157618
project-id = 378696
release-channel = "beta"
