name = "Cheater Deleter"
filename = "cheaterdeleter.jar"
side = "both"

[download]
url = "https://github.com/The-Tiny-Taters/TTTM-AOF/raw/main/mods/jars/cheaterdeleter.jar"
hash-format = "md5"
hash = "dc5e4d603309a5661e65255264f4c510"
