name = "Cloth Config API (Fabric)"
filename = "cloth-config-4.10.13-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3203/816/cloth-config-4.10.13-fabric.jar"
hash-format = "murmur2"
hash = "756600439"

[update]
[update.curseforge]
file-id = 3203816
project-id = 319057
release-channel = "beta"
