name = "Dank Storage Fabric"
filename = "dankstorage-1.9a-1.16.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3124/827/dankstorage-1.9a-1.16.3.jar"
hash-format = "murmur2"
hash = "353002753"

[update]
[update.curseforge]
file-id = 3124827
project-id = 400619
release-channel = "beta"
