name = "Dawn API"
filename = "dawn-1.6.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3192/887/dawn-1.6.5.jar"
hash-format = "murmur2"
hash = "2371526634"

[update]
[update.curseforge]
file-id = 3192887
project-id = 399309
release-channel = "beta"
