name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-fabric-1.16.5-2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3191/163/EnchantmentDescriptions-fabric-1.16.5-2.0.1.jar"
hash-format = "murmur2"
hash = "3979945507"

[update]
[update.curseforge]
file-id = 3191163
project-id = 250419
release-channel = "beta"
