name = "Fabric-Discord Link"
filename = "Fabric-Discord-Link-0.8.8.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3193/923/Fabric-Discord-Link-0.8.8.jar"
hash-format = "murmur2"
hash = "836814446"

[update]
[update.curseforge]
file-id = 3193923
project-id = 318315
release-channel = "beta"
