name = "FabricTPA"
filename = "FabricTPA-1.4.1.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3151/830/FabricTPA-1.4.1.jar"
hash-format = "murmur2"
hash = "3692102760"

[update]
[update.curseforge]
file-id = 3151830
project-id = 423295
release-channel = "beta"
