name = "Fabric Zones"
filename = "fabric-zones-0.0.0-1.16.5.jar"
side = "server"

[download]
url = "https://spaceclouds42.github.io/FabricZones/builds/1.16.5/fabric-zones-0.0.0-1.16.5.jar"
hash-format = "sha256"
hash = "8234081EEBEB4BF232D537182093B78C719E3B77D4D82DA921A6AF95AD79A1BF"