name = "FlytreLib"
filename = "flytre_lib-0.2.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3214/194/flytre_lib-0.2.7.jar"
hash-format = "murmur2"
hash = "360132072"

[update]
[update.curseforge]
file-id = 3214194
project-id = 444498
release-channel = "beta"
