name = "Gift It! (Fabric)"
filename = "giftit.jar"
side = "both"

[download]
url = "https://github.com/The-Tiny-Taters/TTTM-AOF/raw/main/mods/jars/giftit.jar"
hash-format = "sha256"
hash = "9d31a78e98fa3e1c356dcb244b7a1809cdcf5f5d815ff0a99c9b59e84c4d4c61"