name = "Gift It! (Fabric)"
filename = "giftit-1.3.2+mc1.16.5.jar"
side = "both"

[download]
url = "https://www.curseforge.com/minecraft/mc-mods/gift-it/download/3198242/file"
hash-format = "sha256"
hash = "9D31A78E98FA3E1C356DCB244B7A1809CDCF5F5D815FF0A99C9B59E84C4D4C61"

[update]
[update.curseforge]
file-id = 3198242
project-id = 323210
release-channel = "beta"
