name = "Hard Hat Steve"
filename = "hard-hat-steve-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3121/61/hard-hat-steve-1.2.0.jar"
hash-format = "murmur2"
hash = "1935617195"

[update]
[update.curseforge]
file-id = 3121061
project-id = 333779
release-channel = "beta"
