name = "Indium"
filename = "indium.jar"
side = "client"

[option]
optional = true
description = "Fabric rendering api re-implementation, only use if needed. Must include 'Sodium' as well"
default = false

[download]
url = "https://github.com/The-Tiny-Taters/TTTM-AOF/blob/main/mods/jars/indium.jar"
hash-format = "sha256"
hash = "89927E2B17562AC207F76D38DDB9FA9ADF0FC47BB088B64B2B07680688260274"
