name = "Industrial Revolution"
filename = "indrev-1.7.15-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3124/805/indrev-1.7.15-BETA.jar"
hash-format = "murmur2"
hash = "442683977"

[update]
[update.curseforge]
file-id = 3124805
project-id = 391708
release-channel = "beta"
