name = "Inventory Sorting"
filename = "InventorySorter-1.7.6-1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3156/544/InventorySorter-1.7.6-1.16.jar"
hash-format = "murmur2"
hash = "3771334524"

[update]
[update.curseforge]
file-id = 3156544
project-id = 325471
release-channel = "beta"
