name = "Light Overlay (Rift/Forge/Fabric)"
filename = "light-overlay-5.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3204/912/light-overlay-5.7.0.jar"
hash-format = "murmur2"
hash = "3331532444"

[update]
[update.curseforge]
file-id = 3204912
project-id = 325492
release-channel = "beta"
