name = "megane"
filename = "megane-3.1.3+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3208/126/megane-3.1.3+1.16.5.jar"
hash-format = "murmur2"
hash = "3654603894"

[update]
[update.curseforge]
file-id = 3208126
project-id = 408118
release-channel = "beta"
