name = "Modern Industrialization"
filename = "Modern-Industrialization-0.3.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3186/480/Modern-Industrialization-0.3.12.jar"
hash-format = "murmur2"
hash = "1641317092"

[update]
[update.curseforge]
file-id = 3186480
project-id = 405388
release-channel = "beta"
