name = "Mod Menu"
filename = "modmenu-1.14.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3179/43/modmenu-1.14.15.jar"
hash-format = "murmur2"
hash = "2209477758"

[update]
[update.curseforge]
file-id = 3179043
project-id = 308702
release-channel = "beta"
