name = "Mod Menu"
filename = "modmenu-1.16.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3199/797/modmenu-1.16.7.jar"
hash-format = "murmur2"
hash = "3962836138"

[update]
[update.curseforge]
file-id = 3199797
project-id = 308702
release-channel = "beta"
