name = "More Tooltips"
filename = "[1.16.4] MoreTooltips-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3124/331/%5B1.16.4%5D MoreTooltips-1.0.1.jar"
hash-format = "sha256"
hash = "b3b1a441a2e573b433a6b29e523f109fdfe4c03bf8adeca5f05eecf5c2799b3f"

[update]
[update.curseforge]
file-id = 3124331
project-id = 421949
release-channel = "beta"
