name = "Oh The Biomes You'll Go [FABRIC]"
filename = "byg-1.1.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3196/554/byg-1.1.4.jar"
hash-format = "murmur2"
hash = "3977757986"

[update]
[update.curseforge]
file-id = 3196554
project-id = 391378
release-channel = "beta"
