name = "Pingspam"
filename = "pingspam-1.1.0-pre5.jar"
side = "both"

[download]
url = "https://github.com/BasiqueEvangelist/pingspam/releases/download/1.1.0-pre5/pingspam-1.1.0-pre5.jar"
hash-format = "sha256"
hash = "3FE1544A3E16AE9EDB34177BA57135C3ABBF1A41E9EFFE5D343C118CC1CCA30D"
