name = "Pingspam"
filename = "pingspam-1.1.2-pre1.jar"
side = "both"

[download]
url = "https://github.com/BasiqueEvangelist/pingspam/releases/download/1.1.2-pre1/pingspam-1.1.2-pre1.jar"
hash-format = "sha512"
hash = "67223b6d52560d3b7d7256a3864656fa3b899adf3f4f50e8ce5147f9a7bcdcc6"
