name = "Pingspam"
filename = "pingspam-1.1.0-rc2.jar"
side = "both"

[download]
url = "https://github.com/BasiqueEvangelist/pingspam/releases/download/1.1.0-pre2/pingspam-1.1.0-rc2.jar"
hash-format = "sha256"
hash = "03c7e3463e5d5586f4c8fbb490eb5b14c7a7e49f0959d9d45d99d4ff7041e616"
