name = "Sandwichable"
filename = "sandwichable-1.2-beta2--1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3184/245/sandwichable-1.2-beta2--1.16.5.jar"
hash-format = "murmur2"
hash = "818335467"

[update]
[update.curseforge]
file-id = 3184245
project-id = 374143
release-channel = "beta"
