name = "Secret Rooms Fabric"
filename = "secretrooms-0.9.3+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3209/165/secretrooms-0.9.3+1.16.5.jar"
hash-format = "murmur2"
hash = "1451065556"

[update]
[update.curseforge]
file-id = 3209165
project-id = 359248
release-channel = "beta"
