name = "Secret Rooms Fabric"
filename = "secretrooms-0.9.2+1.16.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3030/321/secretrooms-0.9.2+1.16.2.jar"
hash-format = "murmur2"
hash = "374923798"

[update]
[update.curseforge]
file-id = 3030321
project-id = 359248
release-channel = "beta"
