name = "ShulkerBoxTooltip"
filename = "shulkerboxtooltip-2.3.4+1.16.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3172/886/shulkerboxtooltip-2.3.4+1.16.4.jar"
hash-format = "murmur2"
hash = "2424496247"

[update]
[update.curseforge]
file-id = 3172886
project-id = 315811
release-channel = "beta"
