name = "SlotLock"
filename = "slotlock-1.0.1-BETA.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3072/509/slotlock-1.0.1-BETA.jar"
hash-format = "murmur2"
hash = "2666403375"

[update]
[update.curseforge]
file-id = 3072509
project-id = 408366
release-channel = "beta"
