name = "Starry Skies"
filename = "starryskies-1.0.9-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3216/905/starryskies-1.0.9-1.16.5.jar"
hash-format = "murmur2"
hash = "3961624956"

[update]
[update.curseforge]
file-id = 3216905
project-id = 427486
release-channel = "beta"
