name = "Tech Reborn"
filename = "TechReborn-1.16-3.8.1+build.211.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3215/300/TechReborn-1.16-3.8.1+build.211.jar"
hash-format = "murmur2"
hash = "3077594613"

[update]
[update.curseforge]
file-id = 3215300
project-id = 233564
release-channel = "beta"
