name = "Tech Reborn"
filename = "TechReborn-1.16-3.7.3+build.192.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3157/477/TechReborn-1.16-3.7.3+build.192.jar"
hash-format = "murmur2"
hash = "442284672"

[update]
[update.curseforge]
file-id = 3157477
project-id = 233564
release-channel = "beta"
