name = "Territorial"
filename = "territorial-0.0.2.jar"
side = "both"

[download]
url = "https://github.com/profjb58/Territorial-Base/releases/download/v0.0.2/territorial-0.0.2.jar"
hash-format = "sha256"
hash = "0CA96102CADC4F2A6DDD12782F53ED6E8B6D15386DB462A771017DF606175DDC"
