name = "Through the looking glass"
filename = "TTLG-ALPHA.5.jar"
side = "both"

[download]
url = "https://github.com/Dragonoidzero/Through-the-Looking-Glass/releases/download/2.0.0-alpha.5/TTLG-ALPHA.5.jar"
hash-format = "sha256"
hash = "EB9E3712E328D60C18313F1150206BBAD332837F026DA9DD9AFDCE6E7342C1DC"
