name = "Through the looking glass"
filename = "TTLG-ALPHA.6.jar"
side = "both"

[download]
url = "https://github.com/Dragonoidzero/Through-the-Looking-Glass/releases/download/2.0.0-alpha.6/TTLG-ALPHA.6.jar"
hash-format = "sha256"
hash = "45B3D03C6D915CF193DCB1C2E75F5F7BEDDFEB3176536E59B8940D6F83A75E82"
