name = "Through the looking glass"
filename = "TTLG-ALPHA.7.jar"
side = "both"

[download]
url = "https://github.com/Dragonoidzero/Through-the-Looking-Glass/releases/download/2.0.0-alpha.7/TTLG-ALPHA.7.jar"
hash-format = "sha256"
hash = "7AFB7AAB3A189F18ABA085D2A02C9664DDB412F3ED6FB38BB1F9CB896B083C2D"
