name = "TIS-3D"
filename = "TIS-3D-MC1.16.2-Fabric-1.6.1.23.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3156/163/TIS-3D-MC1.16.2-Fabric-1.6.1.23.jar"
hash-format = "murmur2"
hash = "3900555463"

[update]
[update.curseforge]
file-id = 3156163
project-id = 238603
release-channel = "beta"
