name = "True Secret Rooms"
filename = "true-secret-rooms-1.1.2-hotfix.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3142/256/true-secret-rooms-1.1.2-hotfix.jar"
hash-format = "murmur2"
hash = "3173023699"

[update]
[update.curseforge]
file-id = 3142256
project-id = 413207
release-channel = "beta"
