name = "Wild Explorer"
filename = "wild_explorer-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3194/955/wild_explorer-1.3.2.jar"
hash-format = "murmur2"
hash = "2174557159"

[update]
[update.curseforge]
file-id = 3194955
project-id = 399648
release-channel = "beta"
