name = "Wild Explorer"
filename = "wild_explorer-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3148/162/wild_explorer-1.3.1.jar"
hash-format = "murmur2"
hash = "3246667423"

[update]
[update.curseforge]
file-id = 3148162
project-id = 399648
release-channel = "beta"
