name = "WTHIT"
filename = "wthit-2.2.0+1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3195/318/wthit-2.2.0+1.16.5.jar"
hash-format = "murmur2"
hash = "3075691575"

[update]
[update.curseforge]
file-id = 3195318
project-id = 440979
release-channel = "beta"
