name = "Xaero's World Map"
filename = "XaerosWorldMap_1.12.0.2_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3200/213/XaerosWorldMap_1.12.0.2_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "994066691"

[update]
[update.curseforge]
file-id = 3200213
project-id = 317780
release-channel = "beta"
