name = "Xaero's World Map"
filename = "XaerosWorldMap_1.11.11.2_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3190/742/XaerosWorldMap_1.11.11.2_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "35192039"

[update]
[update.curseforge]
file-id = 3190742
project-id = 317780
release-channel = "beta"
